apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: moose3345/docker-apps-app:latest
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: dbhost
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: dbport
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: password
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
