name: On-Demand SAST Scanner

on:
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name : Checkout Code
        uses : actions/checkout@v4

      - name : Run Semgrep
        uses : semgrep/action@v1
        with :
          config : "p/owasp-top-ten"
          generateSarif : "1"
    
    env :
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

          
