name: Semgrep SAST Scanner

on:
  workflow_dispatch:

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    container:
      image: semgrep/semgrep

    steps:
      - name : Checkout Code
        uses : actions/checkout@v4

      - name : Run Semgrep
        run : semgrep ci --sarif --output=semgrep.sarif

      - name : Upload SARIF
        uses : github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
