name: OWASP ZAP DAST Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    name: ZAP DAST Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull ZAP Docker image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk:rw \
            --network host \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t ${{ secrets.TARGET_URL }} \
            -J /zap/wrk/report_json.json \
            -w /zap/wrk/report_md.md \
            -r /zap/wrk/report_html.html \
            -I  # -I = tidak fail meski ada warning
        continue-on-error: true
      
      - name: Verify files
        if: always()
        run: ls -la ${{ github.workspace }}/report_*.*

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report-${{ github.run_id }}
          path: |
            ${{ github.workspace }}/report_html.html
            ${{ github.workspace }}/report_json.json
            ${{ github.workspace }}/report_md.md
          if-no-files-found: warn
